<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>IŽK{if $user->loggedIn} - {$user->identity->id}{/if}</title>
		<link rel="stylesheet" href="{$basePath}/css/blueprint/screen.css" type="text/css" media="screen, projection">
		<link rel="stylesheet" href="{$basePath}/css/blueprint/print.css" type="text/css" media="print">
		<!--[if lt IE 8]><link rel="stylesheet" href="{$basePath}/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

		<link rel="stylesheet" href="{$basePath}/css/screen.css" type="text/css" media="screen, projection">

		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js">
		<script type="text/javascript" src="{$basePath}/js/nette.forms.js"></script>
		<script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>
		<script type="text/javascript" src="{$basePath}/js/izk.js"></script>
	</head>
	<body>
		<div id="header" class="container">
			<div class="span-14">
				<h1>Internetová žiacka knižka</h1>
			</div>
			<div id="nav" class="span-10 last">
				<ul>
					<li n:if="$user->loggedIn"><a n:href="Sign:out">Odhlásiť</a></li>
					<li n:if="!$user->loggedIn"><a n:href="Sign:in">Prihlásiť</a></li>
				</ul>
			</div>
		</div>
		<div id="content" class="container">
			{include #content}
		</div>
		<div id="footer" class="container">
			
		</div>
	</body>
</html>